version: '3.1'

services:

  scrapy:
    build:
      context: ./scrapy
      dockerfile: Dockerfile

    working_dir: /usr/src/app
    restart: no
    tty: true
    stdin_open: true

    volumes:
      - ./scrapy:/usr/src/app
      - ./shared:/usr/src/app/forumford/shared

    networks:
      - global

    ports:
      - 4000:4000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    working_dir: /usr/src/app
    restart: no
    tty: true
    stdin_open: true

    volumes:
      - ./backend:/usr/src/app
      - ./shared:/usr/src/app/shared

    env_file: .env

    networks:
      - global
    ports:
      - 5001:5000

  frontend:
    image: node:18
    working_dir:  /home/node/app
    restart: no
    tty: true
    stdin_open: true

    volumes:
      - ./frontend:/home/node/app

    env_file: .env

    networks:
      - global
    ports:
      - 3000:3000


  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - global
    ports:
      - 55432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - global


volumes:
  postgres_db:


networks:
  global:

