INSERT INTO part_names(category_name, name)
VALUES ('Komfort / wyposażenie wnętrz',	'Linka prędkościomierza'),
       ('Komfort / wyposażenie wnętrz',	'Podnośnik szyby'),
       ('Komfort / wyposażenie wnętrz',	'Potencjometr pedału gazu'),
       ('Komfort / wyposażenie wnętrz',	'Deska rozdzielcza'),
       ('Komfort / wyposażenie wnętrz',	'Dostosowanie siedzenia'),
       ('Komfort / wyposażenie wnętrz',	'Antena'),
       ('Komfort / wyposażenie wnętrz',	'Włącznik zapłonu'),
       ('Komfort / wyposażenie wnętrz',	'Wkladka do zamka'),
       ('Komfort / wyposażenie wnętrz',	'Lusterko wewnętrzne'),
       ('Komfort / wyposażenie wnętrz',	'Korbka szyby'),
       ('Komfort / wyposażenie wnętrz',	'Przełącznik zespolony'),
       ('Komfort / wyposażenie wnętrz',	'Przełącznik szyb'),
       ('Komfort / wyposażenie wnętrz',	'Włącznik drzwiowy'),
       ('Komfort / wyposażenie wnętrz',	'Ogrzewanie siedzeń'),
       ('Ogrzewanie / wentylacja',	'Rezystor dmuchawy'),
       ('Ogrzewanie / wentylacja',	'Wentylator nagrzewnicy'),
       ('Koła pasowe / zębate',	'Koło zmiennych faz rozrządu'),
       ('Ogrzewanie / wentylacja',	'Chłodnica nagrzewnicy'),
       ('Koła pasowe / zębate',	'Koło pasowe pompy wody'),
       ('Przewody / węże',	'Przewody chłodnicy'),
       ('Koła pasowe / zębate',	'Sprzęgło alternatora'),
       ('Przewody / węże',	'Rura intercoolera'),
       ('Napęd pasowy / łańcuchowy',	'Zestaw łańcucha rozrządu'),
       ('Napęd pasowy / łańcuchowy',	'Napinacz paska'),
       ('Napęd pasowy / łańcuchowy',	'Pasek rozrządu'),
       ('Napęd pasowy / łańcuchowy',	'Napinacz łańcucha rozrządu'),
       ('Napęd pasowy / łańcuchowy',	'Pasek klinowy'),
       ('Napęd pasowy / łańcuchowy',	'Łańcuch rozrządu'),
       ('Napęd pasowy / łańcuchowy',	'Rolka napinacza'),
       ('Silnik',	'Miska olejowa'),
       ('Przewody / węże',	'Przewód układu wspomagania'),
       ('Przewody / węże',	'Przewód podciśnienia serwa'),
       ('Koła pasowe / zębate',	'Koło zębate wału korbowego'),
       ('Przewody / węże',	'Przewody paliwowe'),
       ('Silnik',	'Korek wlewu oleju'),
       ('Napęd pasowy / łańcuchowy',	'Zestaw paska rozrządu'),
       ('Silnik',	'Poduszka silnika'),
       ('Silnik',	'Panewki korbowodowe'),
       ('Silnik',	'Oleje silnikowe'),
       ('Silnik',	'Pompa oleju'),
       ('Silnik',	'Głowica'),
       ('Silnik',	'Bagnet oleju'),
       ('Silnik',	'Zestaw montażowy turbosprężarki'),
       ('Silnik',	'Kompletny zestaw uszczelek silnika'),
       ('Silnik',	'Korek spustowy oleju'),
       ('Silnik',	'Dźwigienka zaworowa'),
       ('Komfort / wyposażenie wnętrz',	'Zamek drzwi'),
       ('Silnik',	'Zawór wydechowy'),
       ('Czujniki',	'Czujnik temperatury spalin'),
       ('Czujniki',	'Czujnik temperatury paliwa'),
       ('Czujniki',	'Czujnik temperatury'),
       ('Czujniki',	'Czujnik położenia wału korbowego'),
       ('Czujniki',	'Czujnik położenia wałka rozrządu'),
       ('Czyszczenie szyb',	'Silnik wycieraczek'),
       ('Czyszczenie szyb',	'Mechanizm wycieraczek'),
       ('Czyszczenie szyb',	'Dysze spryskiwaczy'),
       ('Czyszczenie szyb',	'Wycieraczki'),
       ('Czyszczenie szyb',	'Pompka spryskiwacza'),
       ('Elektryka',	'Alternator'),
       ('Elektryka',	'Akumulator'),
       ('Elektryka',	'Klakson'),
       ('Elektryka',	'Akumulatory motocyklowe'),
       ('Elektryka',	'Regulator alternatora'),
       ('Elektryka',	'Silniczek regulacji świateł'),
       ('Filtry',	'Filtr oleju'),
       ('Filtry',	'Filtr powietrza'),
       ('Filtry',	'Filtr paliwa'),
       ('Filtry',	'Filtr kabinowy'),
       ('Karoseria',	'Szyba przednia'),
       ('Karoseria',	'Emblematy'),
       ('Karoseria',	'Siłownik klapy bagażnika'),
       ('Karoseria',	'Światła przeciwmgłowe przednie'),
       ('Karoseria',	'Podłużnica ramy'),
       ('Karoseria',	'Pas przedni'),
       ('Karoseria',	'Klamki do drzwi'),
       ('Karoseria',	'Klapa bagażnika'),
       ('Karoseria',	'Uszczelki szyby'),
       ('Karoseria',	'Szyba boczna'),
       ('Klimatyzacja',	'Czujnik ciśnienia klimatyzacji'),
       ('Klimatyzacja',	'Parownik klimatyzacji'),
       ('Klimatyzacja',	'Zawór rozprężny klimatyzacji'),
       ('Klimatyzacja',	'Osuszacz klimatyzacji'),
       ('Sprzęgło',	'Koło zamachowe dwumasowe'),
       ('Przewody / węże',	'Króciec wody'),
       ('Silnik',	'Pokrywa zaworów'),
       ('Silnik',	'Panewki główne'),
       ('Napęd pasowy / łańcuchowy',	'Rozrząd, Pompa wody + zestaw paska rozrządu'),
       ('Silnik',	'Wałek rozrządu'),
       ('Silnik',	'Zestaw uszczelek głowicy'),
       ('Silnik',	'Czujnik poziomu oleju'),
       ('Skrzynia biegów',	'Uszczelki skrzyni biegów'),
       ('Skrzynia biegów',	'Olej przekładniowy'),
       ('Skrzynia biegów',	'Linka zmiany biegów'),
       ('Skrzynia biegów',	'Czujnik prędkości'),
       ('Skrzynia biegów',	'Olej do automatycznej skrzyni biegów'),
       ('Skrzynia biegów',	'Zestaw naprawczy lewarka zmiany biegów'),
       ('Sprzęgło',	'Łożysko oporowe sprzęgła'),
       ('Sprzęgło',	'Tarcza dociskowa sprzęgła'),
       ('Sprzęgło',	'Pompa sprzęgła'),
       ('Sprzęgło',	'Tarcza sprzęgła'),
       ('Sprzęgło',	'Łożysko pilotujące sprzęgła'),
       ('Sprzęgło',	'Zestaw sprzęgła'),
       ('Sprzęgło',	'Linka sprzęgła'),
       ('Sprzęgło',	'Czujnik sprzęgła'),
       ('Układ chłodzenia silnika',	'Włącznik wentylatora chłodnicy'),
       ('Układ chłodzenia silnika',	'Czujnik temperatury wody'),
       ('Układ chłodzenia silnika',	'Wentylator chłodnicy'),
       ('Układ chłodzenia silnika',	'Chłodnica wody'),
       ('Układ chłodzenia silnika',	'Pompa wody'),
       ('Układ chłodzenia silnika',	'Płyn chłodniczy'),
       ('Układ chłodzenia silnika',	'Termostat układu chłodzenia'),
       ('Układ chłodzenia silnika',	'Korek chłodnicy'),
       ('Układ chłodzenia silnika',	'Intercooler'),
       ('Układ napędowy',	'Wał kardana'),
       ('Układ napędowy',	'Osłona przegubu'),
       ('Układ napędowy',	'Półoś napędowa'),
       ('Układ napędowy',	'Krzyżak przegubu wewnętrznego'),
       ('Układ napędowy',	'Przegub napędowy'),
       ('Układ zapłonowy / żarowy',	'Moduł zapłonowy'),
       ('Układ zapłonowy / żarowy',	'Czujnik spalania stukowego'),
       ('Układ zapłonowy / żarowy',	'Cewka zapłonowa'),
       ('Układ zapłonowy / żarowy',	'Świece żarowe'),
       ('Układ zapłonowy / żarowy',	'Świece zapłonowe'),
       ('Układ zapłonowy / żarowy',	'Przewody zapłonowe'),
       ('Układ zapłonowy / żarowy',	'Palec rozdzielacza'),
       ('Układ hamulcowy',	'Bębny hamulcowe'),
       ('Przekaźniki',	'Przerywacz kierunkowskazów'),
       ('Układ hamulcowy',	'Cylinderek hamulcowy'),
       ('Układ hamulcowy',	'Czujnik abs'),
       ('Układ hamulcowy',	'Czujnik stopu'),
       ('Układ hamulcowy',	'Czujnik zużycia klocków hamulcowych'),
       ('Układ hamulcowy',	'Hamulec bębnowy'),
       ('Układ hamulcowy',	'Hamulec ręczny'),
       ('Układ hamulcowy',	'Jarzmo zacisku'),
       ('Układ hamulcowy',	'Klocki hamulcowe'),
       ('Układ hamulcowy',	'Korektor siły hamowania'),
       ('Układ hamulcowy',	'Linka hamulca ręcznego'),
       ('Układ hamulcowy',	'Osłona tarczy hamulcowej'),
       ('Układ hamulcowy',	'Pierścień ABS'),
       ('Układ hamulcowy',	'Pompa ABS'),
       ('Układ hamulcowy',	'Pompa hamulcowa'),
       ('Układ hamulcowy',	'Pompa vacum'),
       ('Układ hamulcowy',	'Prowadnica zacisku hamulcowego'),
       ('Układ hamulcowy',	'Przewody hamulcowe elastyczne'),
       ('Układ hamulcowy',	'Przewody hamulcowe sztywne'),
       ('Układ hamulcowy',	'Płyn hamulcowy'),
       ('Układ hamulcowy',	'Serwo hamulcowe'),
       ('Układ hamulcowy',	'Szczeki hamulca recznego'),
       ('Układ hamulcowy',	'Szczęki hamulcowe'),
       ('Układ hamulcowy',	'Tarcze hamulcowe'),
       ('Układ hamulcowy',	'Zacisk hamulcowy'),
       ('Układ hamulcowy',	'Zbiornik płynu hamulcowego'),
       ('Układ hamulcowy',	'Zestaw montażowy szczęk hamulcowych'),
       ('Układ hamulcowy',	'Zestaw tarcz i klocków hamulcowych'),
       ('Układ kierowniczy',	'Amortyzator układu kierowniczego'),
       ('Układ kierowniczy',	'Czujnik skrętu kierownicy'),
       ('Układ kierowniczy',	'Drążek kierowniczy'),
       ('Układ kierowniczy',	'Końcówka drążka kierowniczego'),
       ('Układ kierowniczy',	'Olej hydrauliczny'),
       ('Układ kierowniczy',	'Osłona drążka kierowniczego'),
       ('Układ kierowniczy',	'Pompa wspomagania kierownicy'),
       ('Układ kierowniczy',	'Przegub osiowy drążka kierowniczego poprzecznego'),
       ('Układ kierowniczy',	'Przekładnia kierownicza'),
       ('Koła pasowe / zębate',	'Koło pasowe wału korbowego'),
       ('Przekaźniki',	'Przekaźnik wycieraczek'),
       ('Koła pasowe / zębate',	'Sprzęgło sprężarki klimatyzacji'),
       ('Przekaźniki',	'Przekaznik pompy paliwa'),
       ('Napęd pasowy / łańcuchowy',	'Rolka prowadząca'),
       ('Napęd pasowy / łańcuchowy',	'Zestaw paska wielorowkowego'),
       ('Napęd pasowy / łańcuchowy',	'Pasek wielorowkowy'),
       ('Przewody / węże',	'Przewód olejowy turbiny'),
       ('Zawieszenie',	'Nakrętki do felg'),
       ('Zawieszenie',	'Zwrotnica'),
       ('Zawieszenie',	'Tuleja stabilizatora'),
       ('Zawieszenie',	'Tuleje belki'),
       ('Sprzęgło',	'Sprzęgło'),
       ('Amortyzacja',	'Akumulator hydrauliczny'),
       ('Czujniki',	'Przepływomierz powietrza'),
       ('Silnik',	'Kolektor ssący dolot powietrza'),
       ('Sprzęgło',	'Koło zamachowe'),
       ('Czyszczenie szyb',	'Ramię wycieraczki'),
       ('Czyszczenie szyb',	'Zbiorniczek spryskiwacza'),
       ('Czyszczenie szyb',	'Guma wycieraczki'),
       ('Elektryka',	'Akumulatory do ciężarówek'),
       ('Elektryka',	'Włącznik elektromagnetyczny rozrusznika'),
       ('Komfort / wyposażenie wnętrz',	'Nakładki na pedały'),
       ('Komfort / wyposażenie wnętrz',	'Włącznik świateł cofania'),
       ('Komfort / wyposażenie wnętrz',	'Przełącznik świateł'),
       ('Komfort / wyposażenie wnętrz',	'Gałka do zmiany biegów'),
       ('Komfort / wyposażenie wnętrz',	'Czujniki parkowania'),
       ('Komfort / wyposażenie wnętrz',	'Silniczek podnoszenia szyby'),
       ('Ogrzewanie / wentylacja',	'Regulator dmuchawy'),
       ('Czujniki',	'Czujnik przyspieszenia poprzecznego'),
       ('Czujniki',	'Czujnik ciśnienia spalin'),
       ('Filtry',	'Sportowy filtr powietrza'),
       ('Karoseria',	'Nadkole plastikowe'),
       ('Karoseria',	'Wzmocnienie zderzaka'),
       ('Karoseria',	'Światło odblaskowe tylne'),
       ('Klimatyzacja',	'Chłodnica klimatyzacji'),
       ('Klimatyzacja',	'Sprężarka klimatyzacji'),
       ('Przewody / węże',	'Przewódy klimatyzacji'),
       ('Silnik',	'Blok silnika'),
       ('Silnik',	'Pierścienie tłokowe'),
       ('Silnik',	'Pompa powietrza wtórnego'),
       ('Silnik',	'Tłok'),
       ('Silnik',	'Odpowietrzenie skrzyni korbowej'),
       ('Skrzynia biegów',	'Poduszka skrzyni biegów'),
       ('Skrzynia biegów',	'Filtr automatycznej skrzyni biegów'),
       ('Sprzęgło',	'Wysprzęglik centralny sprzęgła'),
       ('Sprzęgło',	'Siłownik sprzęgła'),
       ('Układ chłodzenia silnika',	'Chłodnica oleju silnikowego'),
       ('Układ chłodzenia silnika',	'Zbiornik płynu chłodniczego'),
       ('Układ chłodzenia silnika',	'Sprzęgło wentylatora'),
       ('Układ chłodzenia silnika',	'Korek zbiornika wyrównawczego'),
       ('Układ napędowy',	'Przegub elastyczny wału napędowego'),
       ('Układ zapłonowy / żarowy',	'Kopułka rozdzielacza'),
       ('Układ zapłonowy / żarowy',	'Aparat zapłonowy'),
       ('Układ zapłonowy / żarowy',	'Przekaźnik świec żarowych'),
       ('Zawieszenie',	'Śruby do felg'),
       ('Zawieszenie',	'Łącznik stabilizatora'),
       ('Zawieszenie',	'Łożysko koła'),
       ('Zawieszenie',	'Piasta koła'),
       ('Zawieszenie',	'Sworzeń wahacza'),
       ('Zawieszenie',	'Tuleja wahacza'),
       ('Zawieszenie',	'Zestaw naprawczy wahacza'),
       ('Zawieszenie',	'Wahacz'),
       ('Zawieszenie',	'Dystanse do felg'),
       ('Zawieszenie',	'Dyferencjał'),
       ('Zawieszenie',	'Drążek stabilizatora'),
       ('Zawieszenie',	'Belka skrętna'),
       ('Układ wydechowy',	'DPF Filtr cząstek stałych'),
       ('Amortyzacja',	'Talerz sprężyny'),
       ('Amortyzacja',	'Resory'),
       ('Amortyzacja',	'Odbój i osłona amortyzatora'),
       ('Amortyzacja',	'Zestaw sprężyn zawieszenia'),
       ('Amortyzacja',	'Zestaw zawieszenia'),
       ('Amortyzacja',	'Amortyzatory'),
       ('Amortyzacja',	'Poduszka amortyzatora'),
       ('Amortyzacja',	'Sprężyny zawieszenia'),
       ('Amortyzacja',	'Zawieszenie pneumatyczne'),
       ('Czujniki',	'Czujnik ciśnienia oleju'),
       ('Czujniki',	'Czujnik temperatury oleju'),
       ('Czujniki',	'Czujnik cisnienia doładowania'),
       ('Czujniki',	'Czujnik temperatury powietrza dolotowego'),
       ('Czujniki',	'Czujnik temperatury zewnętrznej'),
       ('Czujniki',	'Przetwornik ciśnienia turbosprężarki'),
       ('Czujniki',	'Regulator biegu jałowego'),
       ('Czujniki',	'Czujnik tpms'),
       ('Elektryka',	'Rozrusznik'),
       ('Karoseria',	'Szkło reflektora'),
       ('Karoseria',	'Szkło lusterka zewnętrznego'),
       ('Karoseria',	'Światła przeciwmgłowe tylne'),
       ('Karoseria',	'Amortyzator pokrywy silnika'),
       ('Karoseria',	'Listwy ozdobne'),
       ('Karoseria',	'Centralny zamek'),
       ('Karoseria',	'Błotnik'),
       ('Karoseria',	'Drzwi pojedyncze czesci'),
       ('Karoseria',	'Dokładka zderzaka'),
       ('Karoseria',	'Dodatkowe światło stopu'),
       ('Karoseria',	'Uszczelka drzwi'),
       ('Karoseria',	'Światła stopu'),
       ('Karoseria',	'Kierunkowskazy'),
       ('Karoseria',	'Oświetlenie tablicy rejestracyjnej'),
       ('Karoseria',	'Światła przednie'),
       ('Karoseria',	'Atrapa chłodnicy'),
       ('Karoseria',	'Światła do jazdy dziennej'),
       ('Karoseria',	'Poszerzenia nadkoli'),
       ('Karoseria',	'Zderzak'),
       ('Karoseria',	'Zamek klapy bagażnika'),
       ('Karoseria',	'Szyba tylna'),
       ('Karoseria',	'Lampy tylne'),
       ('Karoseria',	'Kratka zderzaka'),
       ('Karoseria',	'Hak holowniczy'),
       ('Karoseria',	'Osłona silnika'),
       ('Karoseria',	'Obudowa lusterka'),
       ('Karoseria',	'Próg wewnętrzny'),
       ('Karoseria',	'Swiatla cofania'),
       ('Karoseria',	'Nadkole'),
       ('Karoseria',	'Mocowanie zderzaka'),
       ('Karoseria',	'Maska silnika'),
       ('Karoseria',	'Światła pozycyjne'),
       ('Karoseria',	'Lusterka zewnętrzne'),
       ('Silnik',	'Zestaw uszczelek bloku silnika'),
       ('Silnik',	'Wał korbowy'),
       ('Silnik',	'Zawór ssący'),
       ('Silnik',	'Obudowa rozrządu'),
       ('Silnik',	'Popychacze zaworowe'),
       ('Silnik',	'Śruby głowicy'),
       ('Układ paliwowy',	'Czujnik cisnienia paliwa'),
       ('Układ paliwowy',	'Czujnik poziomu paliwa'),
       ('Układ paliwowy',	'Czujnik położenia przepustnicy'),
       ('Układ paliwowy',	'Korek wlewu paliwa'),
       ('Układ paliwowy',	'Linka gazu'),
       ('Układ paliwowy',	'Podkładka pod wtryskiwacz'),
       ('Układ paliwowy',	'Pompa wtryskowa'),
       ('Układ paliwowy',	'Przepustnica'),
       ('Układ paliwowy',	'Regulator ciśnienia paliwa'),
       ('Układ paliwowy',	'Zbiornik paliwa'),
       ('Układ wydechowy',	'Katalizator'),
       ('Układ wydechowy',	'Końcówka wydechu'),
       ('Układ wydechowy',	'Obejma tłumika'),
       ('Układ wydechowy',	'Rura wydechowa'),
       ('Układ wydechowy',	'Sonda lambda'),
       ('Układ wydechowy',	'Turbosprężarka'),
       ('Układ wydechowy',	'Tłumik końcowy'),
       ('Układ wydechowy',	'Tłumik przedni'),
       ('Układ wydechowy',	'Uszczelka rury wydechowej'),
       ('Układ wydechowy',	'Wieszak tłumika'),
       ('Układ wydechowy',	'Zawór EGR'),
       ('Układ wydechowy',	'Zestaw montażowy kolektora wydechowego'),
       ('Układ wydechowy',	'Zestaw montażowy tłumika'),
       ('Układ wydechowy',	'Łącznik elastyczny wydechu'),
       ('Uszczelki / pierścienie uszczelniające',	'szczelka chłodnicy oleju'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka kolektora ssącego'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka korka spustowego oleju'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka miski olejowej'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka pod głowicą'),
       ('Komfort / wyposażenie wnętrz',	'Czujnik deszczu'),
       ('Układ hamulcowy',	'Tłoczek zacisku hamulcowego'),
       ('Układ hamulcowy',	'Zestaw naprawczy zacisku hamulcowego'),
       ('Układ kierowniczy',	'Kolumna kierownicza + elektryczne wspomaganie kierownicy'),
       ('Układ kierowniczy',	'Płyn wspomagania kierownicy'),
       ('Układ paliwowy',	'Gaznik pojedyncze części'),
       ('Układ paliwowy',	'Pompa paliwa'),
       ('Układ wydechowy',	'Kolektor wydechowy'),
       ('Układ wydechowy',	'Osłona termiczna tłumika'),
       ('Układ wydechowy',	'Tłumik środkowy'),
       ('Układ wydechowy',	'Zestaw montażowy katalizatora'),
       ('Układ wydechowy',	'Zestaw montażowy układu wydechowego'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka kolektora wylotowego'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka pokrywy rozrządu'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka pokrywy zaworów'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka szyberdachu'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelka termostatu'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelniacz wałka rozrządu'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelniacz wału korbowego'),
       ('Uszczelki / pierścienie uszczelniające',	'Uszczelniacze zaworowe'),
       ('Żarówki',	'Oświetlenie wewnętrzne'),
       ('Żarówki',	'Żarówka reflektora'),
       ('Żarówki',	'Żarówka reflektora przeciwmgłowego'),
       ('Układ paliwowy',	'Wtryskiwacze końcówki wtrysków');

